#INSTAll Node
- name: Setup Node.js environment
  uses: actions/setup-node@v1.4.3
  with:
  node-version: 12
  #YArn
  -use: borales/actions-yarn@v2.0.0
   with:
   cmd: install
  #Build React App with yarn 
  -name: Build React App 
  run: yarn build
  #Install Surge 
  -name: Install Surge 
  run: npm install --global surge
  #Deploy 
  -name: Deploy React App to Surge 
  run: surge ./build first_project01.surge.sh --token ${{PROJECT01_SURGE_TOKEN}}
  
